### PR TITLE
sphinx: remove unused nodeAddr

### PR DESCRIPTION
**Pull request by joostjager**

### CODE REVIEW

**Comment by joostjager** [comment]
Requesting review @Roasbeef

**Review by guggero — APPROVED** [review]
LGTM :tada:

**Comment by Roasbeef** [comment]
I think this is a sane change, but it _does_ end up breaking the API for all callers. As an intermediate step, we could _just_ remove the internal field? Or is there some other motivation behind this change?

**Comment by joostjager** [comment]
The goal is to break up the API for all callers, so that the caller code can be simplified as well.

**Comment by ellemouton** [comment]
ah, this has now been addressed in https://github.com/lightningnetwork/lightning-onion/pull/62, 

So i think we can close this now (I dont have perms to close)

**Pull request closed without merging**
